name: Run Playwright Tests

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main] 

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Playwright tests and generate Allure results
        env:
          TEST_PHONE: ${{ secrets.TEST_PHONE }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        # 即使測試失敗，也讓後續繼續執行
        continue-on-error: true
        run: npx playwright test

      - name: Generate Allure HTML report
        if: always()
        run: npx allure generate ./allure-results --clean -o ./playwright-report

      - name: Set Git identity
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Upload report to GitHub Pages
        if: always() && hashFiles('playwright-report/index.html') 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
          publish_branch: gh-pages
          force_orphan: true